on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: test ${{matrix.otp}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    container:
      image: erlang:${{matrix.otp}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        otp:
          - "26.0.2.0"
          - "25.3.2.3"
          - "24.3.4.13"
          - "23.3.4.18"
          - "22.3.4.26"
          - "21.3.8.24"
          - "20.3.8.26"
          - "19.3.6.13"
          - "18.3.4.11"
    steps:
      - uses: actions/checkout@v3
      - run: make test
      - run: make edoc
      - run: REBAR=rebar make test
